In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/survey_results_public.csv')
schema_df = pd.read_csv('../data/survey_results_schema.csv')

In [3]:
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',85)

In [4]:
df.head()

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,285000.0,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,Supabase,Firebase Realtime Database;Supabase,Amazon Web Services (AWS);Netlify;Vercel,Fly.io;Netlify;Render,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Capacitor;Electron;Tauri;Uno Platform;Xamarin,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,iOS;iPadOS;MacOS;Windows;Windows Subsystem for...,MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;...,GitHub Discussions;Linear;Notion;Trello,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord;Signal;Slack;Zoom,ChatGPT,ChatGPT;Neeva AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely","I don't think it's super necessary, but I thin...",Yes,Indifferent,Other (please explain),Somewhat distrust,Learning about a codebase;Writing code;Debuggi...,Writing code;Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,10.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,250000.0,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,NaN,NaN,Amazon Web Services (AWS);Google Cloud;OpenSta...,NaN,NaN,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,Microsoft Teams;Slack;Zoom,Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,23.0,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,Agree,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,NaN,12,7,"Developer, front-end",100 to 499 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,156000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,PostgreSQL;Redis,PostgreSQL;Redis,Cloudflare;Heroku,Cloudflare;Heroku,Node.js;React;Ruby on Rails;Vue.js;WordPress,Node.js;Ruby on Rails;Vue.js,NaN,NaN,Homebrew;npm;Vite;Webpack;Yarn,Homebrew;npm;Vite,IntelliJ IDEA;Vim;Visual Studio Code;WebStorm,IntelliJ IDEA;Vim;WebStorm,iOS;iPadOS;MacOS,iOS;iPadOS;MacOS,Jira,Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",I'm wearing of Stack Overflow using AI.,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,7.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,6,4,"Developer, full-stack",20 to 99 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Philippines,PHP\tPhilippine peso,1320000.0,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,BigQuery;Elasticsearch;MongoDB;PostgreSQL,Elasticsearch;MongoDB;PostgreSQL;Redis;Supabase,Amazon Web Services (AWS);Firebase;Heroku;Netl...,Amazon Web Services (AWS);Cloudflare;Digital O...,Express;Gatsby;NestJS;Next.js;Node.js;React,Express;NestJS;Next.js;Node.js;React;Remix;Vue.js,NaN,NaN,Docker;npm;Webpack;Yarn,Docker;npm;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Other (Please Specify):,Other (Please Specify):,Confluence;Jira;Notion,Confluence;Jira;Notion,Discord;Google Meet;Slack;Zoom,Discord;Google Meet;Slack;Zoom,ChatGPT,ChatGPT,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,No,NaN,Neutral,Using AI to suggest better answer to my questi...,Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Project planning;Testing code;Committing and r...,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,6.0,Agree,Strongly agree,Agree,Agree,Neither agree nor disagree,Agree,Strongly agree,Agree,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0

In [5]:
df['ConvertedCompYearly'].head(15)

0          NaN
1     285000.0
2     250000.0
3     156000.0
4      23456.0
5      96828.0
6     135000.0
7      80000.0
8      64254.0
9          NaN
10         NaN
11     78003.0
12     75000.0
13    150000.0
14    187407.0
Name: ConvertedCompYearly, dtype: float64

In [6]:
df['ConvertedCompYearly'].median()

np.float64(74963.0)

In [7]:
df.median()

TypeError: Cannot perform reduction 'median' with string dtype

In [ ]:
df.describe()

In [ ]:
df['ConvertedCompYearly'].count()

np.int64(48019)

In [ ]:
df['SOAccount']

0        NaN
1        Yes
2        Yes
3        Yes
4         No
        ...
89179    Yes
89180    Yes
89181    NaN
89182     No
89183    Yes
Name: SOAccount, Length: 89184, dtype: str

In [ ]:
df['SOAccount'].value_counts()

SOAccount
Yes                        66282
No                         14618
Not sure/can't remember     6952
Name: count, dtype: int64

In [ ]:
df['OpSysProfessional use'].value_counts()

OpSysProfessional use
Windows                                                                                                               15943
MacOS                                                                                                                 12928
Ubuntu                                                                                                                 5201
Windows;Windows Subsystem for Linux (WSL)                                                                              3934
Ubuntu;Windows                                                                                                         2795
                                                                                                                      ...
Android;Cygwin;Debian;MacOS;Ubuntu;Windows;Windows Subsystem for Linux (WSL)                                              1
Debian;Fedora;iOS;iPadOS;Ubuntu;Windows;Windows Subsystem for Linux (WSL)                                                 1
Arch;BSD;Debian;Fedora;Other Linux-based;Red Hat;Windows;Windows Subsystem for Linux (WSL);Other (Please Specify):        1
Android;Arch;ChromeOS;Fedora;MacOS;Other Linux-based;Red Hat;Solaris;Ubuntu                                               1
BSD;Red Hat;Solaris;Ubuntu;Windows                                                                                        1
Name: count, Length: 2470, dtype: int64

In [ ]:
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID310,Q310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB
3,QID312,Q120,,True,MC,SAVR
4,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
5,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
6,QID127,Age,What is your age? *,True,MC,MAVR
7,QID296,Employment,Which of the following best describes your cur...,False,MC,MAVR
8,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
9,QID297,CodingActivities,Which of the following best describes the code...,False,MC,MAVR
10,QID190,S2,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
11,QID25,EdLevel,Which of the following best describes the high...,True,MC,SAVR
12,QID276,LearnCode,How do you learn to code? Select all that apply.,False,MC,MAVR
13,QID281,LearnCodeOnline,What online resources do you use to learn to c...,False,MC,MAVR
14,QID306,LearnCodeCoursesCert,What online courses or certifications do you u...,False,MC,MAVR
15,QID32,YearsCode,"Including any education, how many years have y...",False,MC,DL
16,QID34,YearsCodePro,"NOT including education, how many years have y...",False,MC,DL
17,QID31,DevType,Which of the following describes your current ...,False,MC,SAVR
18,QID29,OrgSize,Approximately how many people are employed by ...,False,MC,SAVR
19,QID278,PurchaseInfluence,"What level of influence do you, personally, ha...",False,MC,SAVR
20,QID322,TechList,When thinking about new technology purchases a...,False,MC,SAVR
21,QID279,BuyNewTool,"When buying a new tool or software, how do you...",False,MC,MAVR
22,QID6,Country,"Where do you live? <span style=""font-weight: b...",True,MC,DL
23,QID50,Currency,Which currency do you use day-to-day? If your ...,True,MC,DL
24,QID51,CompTotal,What is your current total <b>annual</b> compe...,False,TE,SL
25,QID61,S3,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
26,QID233,Language,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
27,QID262,Database,Which <b>database environments </b>have you do...,False,Matrix,Likert
28,QID263,Platform,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
29,QID264,Webframe,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
30,QID265,MiscTech,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
31,QID275,ToolsTech,Which <b>developer </b><strong>tools for compi...,False,Matrix,Likert
32,QID274,NEWCollabTools,Which <strong>development environments</strong...,False,Matrix,Likert
33,QID71,OpSys,What is the primary <b>operating system</b> in...,False,Matrix,Likert
34,QID282,OfficeStackAsync,Which <b>collaborative work management and/or ...,False,Matrix,Likert
35,QID307,OfficeStackSync,Which <b>communication tools</b> did you use r...,False,Matrix,Likert
36,QID327,AISearch,Which <b>AI-powered search tools</b> did you u...,False,Matrix,Likert
37,QID328,AIDev,Which <b>AI-powered developer tools</b> did yo...,False,Matrix,Likert
38,QID91,S4,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
39,QID266,NEWSOSites,Which of the following Stack Overflow sites ha...,True,MC,MAVR
40,QID100,SOVisitFreq,How frequently would you say you visit Stack O...,False,MC,SAVR
41,QID101,SOAccount,Do you have a Stack Overflow account?,False,MC,SAVR
42,QID102,SOPartFreq,How frequently would you say you participate i...,False,MC,SAVR
43,QID106,SOComm,Do you consider yourself a member of the Stack...,False,MC,SAVR
44,QID313,S5,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
45,QID325,SOAI,Artificial Intelligence (AI) tools have gained...,False,TE,SL
46,QID314,AISelect,Do you currently use AI tools in your developm...,True,MC,SAVR
47,QID315,AISent,How favorable is your stance on using AI tools...,False,MC,SAVR
48,QID324,AIAcc,For the AI tools you use as part of your devel...,False,MC,MAVR
49,QID316,AIBen,How much do you trust the accuracy of the outp...,False,MC,SAVR
50,QID319,AITool,Which parts of your development workflow are y...,False,Matrix,Likert
51,QID320,AINext,Thinking about how your workflow and process c...,False,Matrix,Likert
52,QID321,AIOpen,Please describe how you would expect your work...,False,TE,SL
53,QID295,S6,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
54,QID299,TBranch,"<span style=""font-size:16px;"">Would you like t...",True,MC,SAVR
55,QID287,ICorPM,Are you an individual contributor or people ma...,False,MC,SAVR
56,QID288,WorkExp,How many years of working experience do you have?,False,Slider,HSLIDER
57,QID289,Knowledge,Please rate your level of agreement with the f...,False,Matrix,Likert
58,QID290,Frequency,How frequently do you experience each of the f...,False,Matrix,Likert
59,QID291,TimeSearching,"On an average day, how much time do you typica...",False,MC,SAVR
60,QID292,TimeAnswering,"On an average day, how much time do you typica...",False,MC,SAVR
61,QID304,ProfessionalTech,My company has:,False,MC,MAVR
62,QID326,Industry,What industry is the company you work for in?,False,MC,SAVR
63,QID286,SOTeamsUsage,Does your team use Stack Overflow for Teams?,False,MC,SAVR
64,QID131,S7,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
65,QID132,SurveyLength,How do you feel about the length of the survey...,False,MC,MAVR
66,QID133,SurveyEase,How easy or difficult was this survey to compl...,False,MC,MAVR
67,QID289,Knowledge_1,I have interactions with people outside of my ...,NaN,MC,MAVR
68,QID289,Knowledge_2,Knowledge silos prevent me from getting ideas ...,NaN,MC,MAVR
69,QID289,Knowledge_3,I can find up-to-date information within my or...,NaN,MC,MAVR
70,QID289,Knowledge_4,I am able to quickly find answers to my questi...,NaN,MC,MAVR
71,QID289,Knowledge_5,I know which system or resource to use to find...,NaN,MC,MAVR
72,QID289,Knowledge_6,I often find myself answering questions that I...,NaN,MC,MAVR
73,QID289,Knowledge_7,Waiting on answers to questions often causes i...,NaN,MC,MAVR
74,QID289,Knowledge_8,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
75,QID290,Frequency_1,Needing help from people outside of your immed...,NaN,MC,MAVR
76,QID290,Frequency_2,Interacting with people outside of your immedi...,NaN,MC,MAVR
77,QID290,Frequency_3,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR

In [ ]:
schema_df.columns

Index(['qid', 'qname', 'question', 'force_resp', 'type', 'selector'], dtype='str')

In [ ]:
filt = schema_df['qname'] == 'SOAccount'
schema_df.loc[filt]

,qid,qname,question,force_resp,type,selector
41,QID101,SOAccount,Do you have a Stack Overflow account?,False,MC,SAVR

In [ ]:
schema_df.set_index('qname',inplace=True)

In [ ]:
df['OpSysProfessional use'].value_counts()

OpSysProfessional use
Windows                                                                                                               15943
MacOS                                                                                                                 12928
Ubuntu                                                                                                                 5201
Windows;Windows Subsystem for Linux (WSL)                                                                              3934
Ubuntu;Windows                                                                                                         2795
                                                                                                                      ...
Android;Cygwin;Debian;MacOS;Ubuntu;Windows;Windows Subsystem for Linux (WSL)                                              1
Debian;Fedora;iOS;iPadOS;Ubuntu;Windows;Windows Subsystem for Linux (WSL)                                                 1
Arch;BSD;Debian;Fedora;Other Linux-based;Red Hat;Windows;Windows Subsystem for Linux (WSL);Other (Please Specify):        1
Android;Arch;ChromeOS;Fedora;MacOS;Other Linux-based;Red Hat;Solaris;Ubuntu                                               1
BSD;Red Hat;Solaris;Ubuntu;Windows                                                                                        1
Name: count, Length: 2470, dtype: int64

In [ ]:
# if we want the percentage of these things then we can pass the noramlise = true 
df['OpSysProfessional use'].value_counts(normalize = True)

OpSysProfessional use
Windows                                                                                                               0.202871
MacOS                                                                                                                 0.164506
Ubuntu                                                                                                                0.066181
Windows;Windows Subsystem for Linux (WSL)                                                                             0.050059
Ubuntu;Windows                                                                                                        0.035566
                                                                                                                        ...
Android;Cygwin;Debian;MacOS;Ubuntu;Windows;Windows Subsystem for Linux (WSL)                                          0.000013
Debian;Fedora;iOS;iPadOS;Ubuntu;Windows;Windows Subsystem for Linux (WSL)                                             0.000013
Arch;BSD;Debian;Fedora;Other Linux-based;Red Hat;Windows;Windows Subsystem for Linux (WSL);Other (Please Specify):    0.000013
Android;Arch;ChromeOS;Fedora;MacOS;Other Linux-based;Red Hat;Solaris;Ubuntu                                           0.000013
BSD;Red Hat;Solaris;Ubuntu;Windows                                                                                    0.000013
Name: proportion, Length: 2470, dtype: float64

In [ ]:
# GROUPBY - operation involves some combination of splitting the object , applying the function and Combine the Result

In [ ]:
df['Country'].value_counts()

Country
United States of America                                18647
Germany                                                  7328
India                                                    5625
United Kingdom of Great Britain and Northern Ireland     5552
Canada                                                   3507
                                                        ...
Saint Kitts and Nevis                                       1
Marshall Islands                                            1
Samoa                                                       1
Central African Republic                                    1
San Marino                                                  1
Name: count, Length: 185, dtype: int64

In [ ]:
country_grp = df.groupby('Country')

In [ ]:
country_grp.get_group('India')

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
9,10,I agree,I am a developer by profession,25-34 years old,"Not employed, but looking for work",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,edX;Udemy;Pluralsight;Coursera;Udacity,6,NaN,"Developer, full-stack",NaN,NaN,Investigate,Start a free trial;Research companies that hav...,India,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,HTML/CSS;JavaScript;TypeScript,Cloud Firestore;MongoDB;MySQL;PostgreSQL;SQLite,Cloud Firestore;Firebase Realtime Database;Mon...,Amazon Web Services (AWS);Firebase;Google Clou...,Cloudflare;Firebase;Google Cloud;IBM Cloud Or ...,Angular;Express;NestJS;React,Deno;Express;FastAPI;Fastify;NestJS;Qwik;React...,NaN,NaN,Docker;npm;Vite;Webpack;Yarn,Docker;npm;Podman;Vite;Webpack;Yarn,Visual Studio Code,Visual Studio Code,Fedora;Other Linux-based;Ubuntu;Windows;Window...,Fedora;Other Linux-based;Red Hat;Windows;Windo...,Asana;Markdown File;Miro;Notion;Redmine;Trello,Asana;Markdown File;Miro;Notion;Redmine;Trello,Discord;Google Chat;Google Meet;Slack;Telegram,Discord;Google Chat;Google Meet;Telegram,Bing AI;ChatGPT,Bing AI;ChatGPT;Google Bard AI,AWS CodeWhisperer;GitHub Copilot;Tabnine,AWS CodeWhisperer;GitHub Copilot,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Neutral,AI could assist solving communication issues p...,Yes,Indifferent,Other (please explain);Increase productivity;G...,Neither trust nor distrust,Learning about a codebase;Documenting code;Com...,Writing code;Debugging and getting help,Project planning;Testing code;Deployment and m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
66,67,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Online Courses or Certification;School (i.e., ...",NaN,Codecademy;Udemy;Coursera,10,6,"Engineer, data",100 to 499 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,India,INR\tIndian rupee,3400000.0,Java;Scala;SQL,Go;Java;Scala;SQL,BigQuery;MariaDB;MongoDB;MySQL;PostgreSQL,BigQuery;Cassandra;Clickhouse;Dynamodb;MariaDB...,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Apache Kafka;Apache Spark;Hadoop,Apache Kafka;Apache Spark;Hadoop,Docker;Gradle;Homebrew;Kubernetes;Maven (build...,Ansible;Chef;Composer;Docker;Gradle;Homebrew;K...,Atom;IntelliJ IDEA;Jupyter Notebook/JupyterLab...,Atom;IntelliJ IDEA;Jupyter Notebook/JupyterLab...,Android;Debian;iOS;iPadOS;MacOS;Ubuntu;Windows,MacOS,Jira;Markdown File,Jira;Markdown File,Cisco Webex Teams;Discord;Google Chat;Google M...,Cisco Webex Teams;Discord;Google Chat;Google M...,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Collectives on S...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,41197.0
78,79,I agree,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Online Courses or Certification;School (i.e., ...",NaN,Udemy,5,3,"Developer, full-stack",20 to 99 employees,I have little or no influence,NaN,Visit developer communities like Stack Overflow,India,INR\tIndian rupee,NaN,JavaScript;TypeScript,JavaScript;TypeScript,MySQL,MongoDB,Amazon Web Services (AWS),Amazon Web Services (AWS),Angular;Next.js;Node.js,Next.js;Node.js;React,React Native,React Native,NaN,NaN,Visual Studio Code,Visual Studio Code,MacOS,MacOS,Jira,Jira,Slack,Slack,ChatGPT,ChatGPT,NaN,NaN,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"Yes, definitely",NaN,Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Testing code;Committing and reviewing code;Dep...,Writing code,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
82,83,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Codecademy;Udemy;Coursera,10,5,"Developer, game or graphics","10,000 or more employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,India,INR\tIndian rupee,NaN,C++,C++,NaN,NaN,VMware,VMware,NaN,NaN,Opencv;OpenGL;Pandas;Scikit-Learn;TensorFlow,NumPy;Opencv;OpenGL;Pandas;Qt;Scikit-Learn;Ten...,GNU GCC;Make;Pip,GNU GCC;Make;npm;Pip,Eclipse;IntelliJ IDEA;Notepad++;PyCharm;Sublim...,Eclipse;IntelliJ IDEA;Notepad++;PyCharm;Sublim...,Red Hat,Red Hat,Confluence;Doxygen;Jira;Microsoft Planner,Confluence;Doxygen;Jira;Microsoft Planner,Cisco Webex Teams;Google Meet;Microsoft Teams;...,Cisco Webex Teams;Google Meet;Microsoft Teams;...,ChatGPT,ChatGPT,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per month or weekly,Neutral,providing exact copy paste code,"No, but I plan to soon",Very favorable,NaN,Somewhat trust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,5.0,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,Strongly agree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Neither easy nor difficult,NaN
85,86,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Other (please specify):,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,edX;Coursera,7,5,"Developer, back-end",20 to 99 employees,I have a great deal of influence,Investigate,Visit developer communities like Stack Overflo...,India,INR\tIndian rupee,NaN,Assembly;C;C++;Java;JavaScript;SQL,Assembly;C;C++;Java;JavaScript;SQL,Elasticsearch;H2;MySQL;Oracle;PostgreSQL;Redis...,Elasticsearch;H2;MySQL;Oracle;PostgreSQL;Redis...,Amazon Web Services (AWS);Firebase,Amazon Web Services (AWS);Firebase,Angular;Spring Boot,Angular;Spring Boot,Spring Framework,Spring Framework,Ant,Ant,IntelliJ IDEA,IntelliJ IDEA,ChromeOS;Fedora;Other Linux-based;Ubuntu,ChromeOS;Fedora;Other Linux-based;Ubuntu,Asana;Jira,Asana;Jira,Skype;Slack;Telegram;Whatsapp,Skype;Telegram;Whatsapp,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, definitely",NaN,"No, but I plan to soon",Unsure,NaN,Somewhat trust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,6.0,Agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Disagree,Agree,Disagree,10+ times a week,10+ times a week,10+ times a week,30-60 minutes a day,60-120 minutes a day,Automated testing;Continuous integration (CI) ...,Financial Services,Too long,Neither easy nor difficult,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89119,89120,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time",Remote,Hobby;Professional development or self-paced l...,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,NaN,3,NaN,"Developer, mobile",NaN,NaN,NaN,NaN,India,NaN,NaN,Dart;HTML/CSS;JavaScript;Python,Dart;HTML/CSS;JavaScript;Python;Rust;Solidity;...,Cloud Firestore;MongoDB,Cloud Firestore;Firebase Realtime Database;Sup...,Amazon Web Services (AWS);Firebase;Vercel,Amazon Web Services (AWS);Firebase;Google Clou...,Flask;Next.js;React,Next.js;Remix;Svelte;Vue.js,Flutter;NumPy;Pandas;Scikit-Learn,Flutter;NumPy;Opencv;OpenGL;Pandas;Scikit-Learn,npm;Pacman;Pip;Vite;Yarn,Docker;Kubernetes;npm;Pacman;Pip;Unreal Engine...,Android Studio;IntelliJ IDEA;IPython;Jupyter N...,Android Studio;IPython;Jupyter Notebook/Jupyte...,Android;Ubuntu,Android;Ubuntu,GitHub Discussions;Notion,GitHub Discussions;Jira;Notion,Discord;Google Meet;Microsoft Teams;Telegram;W...,Discord;Google Meet;Slack;Telegram;Whatsapp;Zoom,ChatGPT;Google Bard AI;Perplexity AI;WolframAl...,ChatGPT;Google Bard AI;Perplexity AI;You.com,AWS CodeWhisperer;GitHub Copilot,AWS CodeWhisperer;GitHub Copilot,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, definitely",NaN,Yes,Favorable,Increase productivity;Greater efficiency,Somewhat trust,Learning about a codebase;Project planning;Tes...,Writing code;Debugging and getting help,NaN,NaN,Debugging and getting help,NaN,NaN,Writing code;Debugging and getting help,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89121,89122,I agree,"I am not primarily a developer, but I write co...",18-24 years old,"Employed, full-time;Student, part-time","Hybrid (some remote, some in-person)",Contribute to open-source projects;Professiona...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Hackathons (virtual or in-person);Online Cours...,Formal documentation provided by the owner of ...,Coursera,4,NaN,Data scientist or machine learning specialist,NaN,NaN,Investigate,Ask developers I know/work with;Visit develope...,India,NaN,NaN,Python;SQL,Bash/Shell (all shells);Java;Python;SQL,MariaDB;MySQL;PostgreSQL;Snowflake,BigQuery;Dynamodb;MongoDB;MySQL;PostgreSQL;Sno...,Amazon Web Services (AWS),Amazon Web Services (AWS);Google Cloud;Microso...,Flask,FastAPI;Flask,NumPy;Pandas;Scikit-Learn;TensorFlow,Opencv;Pandas;Scikit-Learn;TensorFlow;Torch/Py...,NaN,NaN,Jupyter Notebook/JupyterLab;Visual Studio Code,Jupyter Notebook/JupyterLab;Visual Studio Code,Arch;Debian;Other Linux-based;Windows,Arch;Debian;Other Linux-based;Ubuntu,NaN,NaN,Discord;Google Meet;Microsoft Teams;Skype;Slack,Discord;Slack;Telegram,You.com,ChatGPT;Google Bard AI;You.com,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",NaN,"No, but I plan to soon",Indifferent,NaN,Neither trust nor distrust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
89164,89165,I agree,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Professional development or self-paced learnin...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,Other;Udemy,6,2,"Developer, back-end",20 to 99 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,India,INR\tIndian rupee,NaN,Go;HTML/CSS;Java;JavaScript;Python,Go;Python;Rust,Dynamodb;Elasticsearch;Firebase Realtime Datab...,MongoDB;PostgreSQL,Amazon Web Services (AWS);Google Cloud;Hetzner,Amazon Web Services (AWS),Django;Express;FastAPI;Flask;Node.js;React,Django;FastAPI;Flask,Flutter;NumPy;Opencv;OpenGL;Pandas;RabbitMQ,NumPy;Opencv;Pandas,Docker;Kubernetes;npm;Pip;Yarn,Ansible;Docker;Kubernetes;Pip;Terraform,Android Studio;Atom;Fleet;Goland;IntelliJ IDEA...,PyCharm;Visual Studio Code,Ubuntu;Windows;Windows Subsystem for Linux (WSL),MacOS;Ubuntu,Jira,Jira,Google Meet;Slack;Zoom,Google Meet;Slack;Zoom,ChatGPT,ChatGPT,GitHub Copilot,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",NaN,Yes,Favorable,Increase productivity;Greater efficiency;Impro...,Somewhat trust,Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,2.0,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Never,1-2 times a week,Never,Less than 15 minutes a day,Less than 15 minutes a day,DevOps function;Microservices;Automated testin...,Financial Services,Appropriate in length,Neither easy nor difficult,NaN
89165,89166,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Hobby;Contribute to open-source projects;Profe...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,Udemy,6,3,"Developer, back-end","1,000 to 4,999 employees",I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,India,INR\tIndian rupee,NaN,C;C#;C++;Java;JavaScript;TypeScript,Dart;Elixir;Go;JavaScript;Python;Rust;Solidity...,Cloud Firestore;MongoDB;PostgreSQL;Redis,Dynamodb;Elasticsearch;MongoDB;MySQL;PostgreSQ...,Amazon Web Services (AWS);Firebase;Heroku,Amazon Web Services (AWS);Firebase,Angular;Django;Express;NestJS;Node.js;React,Deno;Express;Fastify;NestJS;Next.js;Node.js;Re...,NaN,NaN,Docker;Homebrew;npm;Pip;Unity 3D;Webpack;Yarn,Bun;Docker;Homebrew;npm;Yarn,Android Studio;Atom;Code::Blocks;Eclipse;Intel...,Nano;Vim;Visual Studio Code,Android;Debian;MacOS;Ubuntu;Windows,Android;Arch;ChromeOS;Fedora;MacOS;Other Linux...,Monday.com;Trello,GitHub Discussions;Monday.com;Stack Overflow f...,Discord;Google Meet;Microsoft Teams;Skype;Slac...,Discord;Google Meet;Microsoft Teams;Skype;Slac...,Bing AI;ChatGPT,ChatGPT;Google Bard AI,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",I think StackOverflow should also use AI to ge...,Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Learning about a codebase;Project planning;Wri...,Learning about a codebase;Project planning;Wri...,NaN,Writing code;Debugging and getting help,NaN,NaN,NaN,Learning about a codebase;Project planning;Wri...,Yes,Individual contributor,3.0,Agree,Neither agree nor disagree,Strongly disagree,Agree,Strongly agree,Neither agree nor disagree,Strongly agree,Strongly agree,1-2 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Observability tools;Innersource initiative;Dev...,"Information Services, IT, Software Development...",Appropriate in length,Neither easy nor difficult,NaN
89167,89168,I agree,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Hobby;Bootstrapping a business;Professional de...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,edX;Udemy;Coursera,6,2,"Developer, mobile",20 to 99 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,India,INR\tIndian rupee,1300000.0,Dart;HTML/CSS;JavaScript;TypeScript,Dart;Go;HTML/CSS;JavaScript;Swift;TypeScript,MongoDB;MySQL;PostgreSQL;SQLite,Cockroachdb;MongoDB;MySQL;PostgreSQL;SQLite,NaN,NaN,Express;Node.js;React;Svelte,Deno;Express;FastAPI;Next.js;Node.js;Svelte,Flutter;NumPy;Pandas;Scikit-Learn,Capacitor;Flutter;JAX;NumPy;Pandas;React Nativ...,Homebrew;Vite,Docker;Homebrew;Podman;Vite,Android Studio;Jupyter Notebook/JupyterLab;Sub...,Jupyter Notebook/JupyterLab;Sublime Text;Visua...,Android;MacOS,Android;MacOS,NaN,NaN,Google Meet;Slack,Google Meet;Slack,ChatGPT,Bing AI;ChatGPT,NaN,NaN,Stack Overflow;Stack Exchange,Daily or almost daily,Not sure/can't remember,NaN,"No, not really","It's should,it will make stackoverflow better ...",Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Writing code;Debugging and getting help;Commit...,Project planning;Writing code;Debugging and ge...,NaN,NaN,NaN,NaN,NaN,Project planning;Writing code;Debugging and ge...,Yes,Individual contributor,2.0,Agree,Neither agree nor disagree,Neither agree nor disagree,Agree,Agree,Agree,Strongly agree,Agree,1-2 times a week,1-2 times a week,NaN,Over 120 minutes a day,30-60 minutes a day,Automated testing,Retail and Consumer Services,Appropriate in length,Neither easy nor difficult,15752.0

In [ ]:
filt = df['Country'] == 'India'
df.loc[filt]['EdLevel'].value_counts()

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          3452
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        993
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     582
Some college/university study without earning a degree                                 348
Primary/elementary school                                                              113
Something else                                                                          63
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          54
Associate degree (A.A., A.S., etc.)                                                     20
Name: count, dtype: int64

In [ ]:
country_grp['EdLevel'].value_counts().head(50)

Country              EdLevel
Afghanistan          Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                           20
                     Something else                                                                         13
                     Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)      8
                     Associate degree (A.A., A.S., etc.)                                                     6
                     Primary/elementary school                                                               6
                     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                         5
                     Some college/university study without earning a degree                                  4
                     Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          2
Albania              Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                           26
                     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        15
                     Some college/university study without earning a degree                                  6
                     Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)      5
                     Associate degree (A.A., A.S., etc.)                                                     2
                     Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          2
                     Primary/elementary school                                                               2
                     Something else                                                                          2
Algeria              Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        40
                     Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                           13
                     Some college/university study without earning a degree                                 12
                     Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          6
                     Primary/elementary school                                                               4
                     Associate degree (A.A., A.S., etc.)                                                     4
                     Something else                                                                          3
                     Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)      3
Andorra              Some college/university study without earning a degree                                  4
                     Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                            3
                     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                         2
                     Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)      2
                     Something else                                                                          2
                     Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          1
                     Associate degree (A.A., A.S., etc.)                                                     1
                     Primary/elementary school                                                               1
Angola               Primary/elementary school                                                               3
                     Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                            3
                     Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)      3
                     Something else                                                                          1
                     Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          1
                     Some college/university study without earning a degree                                  1
                     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                         1
Antigua and Barbuda  Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          2
                     Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)      2
                     Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                            1
                     Associate degree (A.A., A.S., etc.)                                                     1
                     Something else                                                                          1
Argentina            Some college/university study without earning a degree                                245
                     Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          119
                     Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     67
                     Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        56
                     Associate degree (A.A., A.S., etc.)                                                    36
                     Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         32
Name: count, dtype: int64

In [ ]:
country_grp['EdLevel'].value_counts().loc['India']

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          3452
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        993
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     582
Some college/university study without earning a degree                                 348
Primary/elementary school                                                              113
Something else                                                                          63
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                          54
Associate degree (A.A., A.S., etc.)                                                     20
Name: count, dtype: int64

In [ ]:
country_grp['CompTotal'].median()

Country
Afghanistan                                 62333.0
Albania                                    104850.0
Algeria                                    540000.0
Andorra                                    120000.0
Angola                                    2600000.0
                                           ...
Venezuela, Bolivarian Republic of...        14400.0
Viet Nam                                200000000.0
Yemen                                        9000.0
Zambia                                      84000.0
Zimbabwe                                    12500.0
Name: CompTotal, Length: 185, dtype: float64

In [ ]:
# for a specific country median salary 
country_grp['CompTotal'].median().loc['India']

np.float64(1450000.0)

In [ ]:
country_grp['CompTotal'].agg(['median','mean'])

                                           median          mean
Country
Afghanistan                               62333.0  6.666117e+07
Albania                                  104850.0  1.185178e+06
Algeria                                  540000.0  7.836667e+05
Andorra                                  120000.0  1.562473e+09
Angola                                  2600000.0  2.600000e+06
...                                           ...           ...
Venezuela, Bolivarian Republic of...      14400.0  2.482463e+04
Viet Nam                              200000000.0  3.287808e+08
Yemen                                      9000.0  2.252071e+06
Zambia                                    84000.0  1.507400e+05
Zimbabwe                                  12500.0  2.674000e+04

[185 rows x 2 columns]

In [ ]:
country_grp['CompTotal'].agg(['median','mean']).loc['India']

median    1.450000e+06
mean      1.205815e+07
Name: India, dtype: float64

In [ ]:
filt = df['Country'] == 'India'
df.loc[filt]['LanguageHaveWorkedWith'].str.contains('Python').sum()

np.int64(2793)

In [ ]:
country_grp['LanguageHaveWorkedWith'] # series groupBy object

In [ ]:
country_grp['LanguageHaveWorkedWith'].apply(lambda x : x.str.contains('Python').sum())

Country
Afghanistan                              22
Albania                                  19
Algeria                                  35
Andorra                                   5
Angola                                    4
                                       ...
Venezuela, Bolivarian Republic of...     42
Viet Nam                                174
Yemen                                     8
Zambia                                   11
Zimbabwe                                 19
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

In [ ]:
country_respondent = df['Country'].value_counts()
country_respondent

Country
United States of America                                18647
Germany                                                  7328
India                                                    5625
United Kingdom of Great Britain and Northern Ireland     5552
Canada                                                   3507
                                                        ...
Saint Kitts and Nevis                                       1
Marshall Islands                                            1
Samoa                                                       1
Central African Republic                                    1
San Marino                                                  1
Name: count, Length: 185, dtype: int64

In [ ]:
country_uses_python = country_grp['LanguageHaveWorkedWith'].apply(lambda x : x.str.contains('Python').count())
country_uses_python

Country
Afghanistan                              64
Albania                                  60
Algeria                                  85
Andorra                                  16
Angola                                   13
                                       ...
Venezuela, Bolivarian Republic of...    106
Viet Nam                                390
Yemen                                    20
Zambia                                   26
Zimbabwe                                 34
Name: LanguageHaveWorkedWith, Length: 185, dtype: int64

In [ ]:
python_df = pd.concat([country_respondent,country_uses_python],axis='columns',sort=False)
python_df.rename(columns={'count':'NumRespondents','LanguageHaveWorkedWith':'NumKnowsPython'},inplace=True)

In [ ]:
python_df['PctknowsPython'] = (python_df['NumKnowsPython']/python_df['NumRespondents']) * 100
python_df

,NumRespondents,NumKnowsPython,PctknowsPython
Country,,,
United States of America,18647,18647,100.0
Germany,7328,7328,100.0
India,5625,5625,100.0
United Kingdom of Great Britain and Northern Ireland,5552,5552,100.0
Canada,3507,3507,100.0
...,...,...,...
Saint Kitts and Nevis,1,1,100.0
Marshall Islands,1,1,100.0
Samoa,1,1,100.0
Central African Republic,1,1,100.0
San Marino,1,1,100.0

In [ ]:
python_df.sort_values(by='PctknowsPython',ascending=False,inplace=True)
python_df.describe()

       NumRespondents  NumKnowsPython  PctknowsPython
count      185.000000      185.000000           185.0
mean       475.529730      475.529730           100.0
std       1632.132807     1632.132807             0.0
min          1.000000        1.000000           100.0
25%          9.000000        9.000000           100.0
50%         53.000000       53.000000           100.0
75%        317.000000      317.000000           100.0
max      18647.000000    18647.000000           100.0

In [ ]:
python_df.loc['India']

NumRespondents    5625.0
NumKnowsPython    5625.0
PctknowsPython     100.0
Name: India, dtype: float64