In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/ETH_1h.csv', parse_dates= ['Date'], date_format = '%Y-%m-%d %I-%p')

In [3]:
df.head()

                 Date  Symbol    Open    High     Low   Close      Volume
0 2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1 2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2 2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3 2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4 2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [4]:
df.shape

(23674, 7)

In [5]:
df.loc[0,'Date']

Timestamp('2020-03-13 20:00:00')

In [6]:
#df['Date'] = pd.to_datetime(df['Date'],format= '%Y-%m-%d %I-%p')

In [7]:
#df['Date']

In [8]:
df.loc[0,'Date'].day_name()

'Friday'

In [9]:
# we can covert the csv while importing it to datetime column - as it is in str - datetime format and can pass the format string as well

In [10]:
df['Date'].dt.day_name()

0          Friday
1          Friday
2          Friday
3          Friday
4          Friday
           ...
23669    Saturday
23670    Saturday
23671    Saturday
23672    Saturday
23673    Saturday
Name: Date, Length: 23674, dtype: str

In [11]:
df['DayOfWeek'] = df['Date'].dt.day_name()

In [12]:
df

,Date,Symbol,Open,High,Low,Close,Volume,DayOfWeek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
23669,2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
23670,2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
23671,2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
23672,2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
23673,2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [13]:
 df['Date'].min()

Timestamp('2017-07-01 11:00:00')

In [14]:
df['Date'].max()

Timestamp('2020-03-13 20:00:00')

In [15]:
df['Date'].max() - df['Date'].min()

Timedelta('986 days 09:00:00')

In [16]:
# filt = (df['Date'] >= '2019') & (df['Date'] < '2020')
filt = (df['Date'] >= pd.to_datetime('2019-01-01')) & (df['Date'] < pd.to_datetime('2020-01-01'))

In [17]:
df.loc[filt]

,Date,Symbol,Open,High,Low,Close,Volume,DayOfWeek
1749,2019-12-31 23:00:00,ETHUSD,128.33,128.69,128.14,128.54,440678.91,Tuesday
1750,2019-12-31 22:00:00,ETHUSD,128.38,128.69,127.95,128.33,554646.02,Tuesday
1751,2019-12-31 21:00:00,ETHUSD,127.86,128.43,127.72,128.38,350155.69,Tuesday
1752,2019-12-31 20:00:00,ETHUSD,127.84,128.34,127.71,127.86,428183.38,Tuesday
1753,2019-12-31 19:00:00,ETHUSD,128.69,128.69,127.60,127.84,1169847.84,Tuesday
...,...,...,...,...,...,...,...,...
10504,2019-01-01 04:00:00,ETHUSD,130.75,133.96,130.74,131.96,2791135.37,Tuesday
10505,2019-01-01 03:00:00,ETHUSD,130.06,130.79,130.06,130.75,503732.63,Tuesday
10506,2019-01-01 02:00:00,ETHUSD,130.79,130.88,129.55,130.06,838183.43,Tuesday
10507,2019-01-01 01:00:00,ETHUSD,131.62,131.62,130.77,130.79,434917.99,Tuesday
10508,2019-01-01 00:00:00,ETHUSD,130.53,131.91,130.48,131.62,1067136.21,Tuesday

In [26]:
# df.set_index('Date',inplace=True)
# df.sort_index('Date',inplace=True)
df.index

DatetimeIndex(['2020-03-13 20:00:00', '2020-03-13 19:00:00',
               '2020-03-13 18:00:00', '2020-03-13 17:00:00',
               '2020-03-13 16:00:00', '2020-03-13 15:00:00',
               '2020-03-13 14:00:00', '2020-03-13 13:00:00',
               '2020-03-13 12:00:00', '2020-03-13 11:00:00',
               ...
               '2017-07-01 20:00:00', '2017-07-01 19:00:00',
               '2017-07-01 18:00:00', '2017-07-01 17:00:00',
               '2017-07-01 16:00:00', '2017-07-01 15:00:00',
               '2017-07-01 14:00:00', '2017-07-01 13:00:00',
               '2017-07-01 12:00:00', '2017-07-01 11:00:00'],
              dtype='datetime64[us]', name='Date', length=23674, freq=None)

In [28]:
df.sort_index(inplace=True)

In [30]:
# df['2020-01':'2020-02']
df['2020-01':'2020-02']['Close']

Date
2020-01-01 00:00:00    128.34
2020-01-01 01:00:00    130.14
2020-01-01 02:00:00    130.37
2020-01-01 03:00:00    129.57
2020-01-01 04:00:00    129.56
                        ...
2020-02-29 19:00:00    225.31
2020-02-29 20:00:00    224.63
2020-02-29 21:00:00    223.48
2020-02-29 22:00:00    223.35
2020-02-29 23:00:00    217.31
Name: Close, Length: 1440, dtype: float64