In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/survey_results_public.csv')
schema_df = pd.read_csv('../data/survey_results_schema.csv')

In [3]:
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',85)

In [4]:
df.head()

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,285000.0,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,Supabase,Firebase Realtime Database;Supabase,Amazon Web Services (AWS);Netlify;Vercel,Fly.io;Netlify;Render,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Capacitor;Electron;Tauri;Uno Platform;Xamarin,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,iOS;iPadOS;MacOS;Windows;Windows Subsystem for...,MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;...,GitHub Discussions;Linear;Notion;Trello,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord;Signal;Slack;Zoom,ChatGPT,ChatGPT;Neeva AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely","I don't think it's super necessary, but I thin...",Yes,Indifferent,Other (please explain),Somewhat distrust,Learning about a codebase;Writing code;Debuggi...,Writing code;Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,10.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,250000.0,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,NaN,NaN,Amazon Web Services (AWS);Google Cloud;OpenSta...,NaN,NaN,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,Microsoft Teams;Slack;Zoom,Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,23.0,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,Agree,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,NaN,12,7,"Developer, front-end",100 to 499 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,156000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,PostgreSQL;Redis,PostgreSQL;Redis,Cloudflare;Heroku,Cloudflare;Heroku,Node.js;React;Ruby on Rails;Vue.js;WordPress,Node.js;Ruby on Rails;Vue.js,NaN,NaN,Homebrew;npm;Vite;Webpack;Yarn,Homebrew;npm;Vite,IntelliJ IDEA;Vim;Visual Studio Code;WebStorm,IntelliJ IDEA;Vim;WebStorm,iOS;iPadOS;MacOS,iOS;iPadOS;MacOS,Jira,Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",I'm wearing of Stack Overflow using AI.,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,7.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,6,4,"Developer, full-stack",20 to 99 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Philippines,PHP\tPhilippine peso,1320000.0,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,BigQuery;Elasticsearch;MongoDB;PostgreSQL,Elasticsearch;MongoDB;PostgreSQL;Redis;Supabase,Amazon Web Services (AWS);Firebase;Heroku;Netl...,Amazon Web Services (AWS);Cloudflare;Digital O...,Express;Gatsby;NestJS;Next.js;Node.js;React,Express;NestJS;Next.js;Node.js;React;Remix;Vue.js,NaN,NaN,Docker;npm;Webpack;Yarn,Docker;npm;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Other (Please Specify):,Other (Please Specify):,Confluence;Jira;Notion,Confluence;Jira;Notion,Discord;Google Meet;Slack;Zoom,Discord;Google Meet;Slack;Zoom,ChatGPT,ChatGPT,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,No,NaN,Neutral,Using AI to suggest better answer to my questi...,Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Project planning;Testing code;Committing and r...,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,6.0,Agree,Strongly agree,Agree,Agree,Neither agree nor disagree,Agree,Strongly agree,Agree,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0

In [15]:
df.sort_values(by=['Country','CompTotal'],ascending=[True,False],inplace=True)

In [16]:
df[['Country','CompTotal']].head(100)

           Country    CompTotal
88347  Afghanistan  932464379.0
1334   Afghanistan     210000.0
57361  Afghanistan     200000.0
17872  Afghanistan     100000.0
36048  Afghanistan      80000.0
...            ...          ...
64156      Albania          NaN
64081      Albania          NaN
34270      Albania          NaN
19653      Albania          NaN
12812      Albania          NaN

[100 rows x 2 columns]

In [17]:
# N largest salaries

In [18]:
df['CompTotal'].nlargest(10)

56322    5.000000e+46
18463    1.000000e+21
43556    1.000000e+16
49553    1.000000e+16
35779    1.000000e+15
15439    4.567887e+12
33078    1.000000e+11
19679    2.239672e+10
56853    1.980000e+10
9175     1.840199e+10
Name: CompTotal, dtype: float64

In [19]:
df.nlargest(10,'CompTotal')

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
56322,56323,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Hobby;Contribute to open-source projects;Boots...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Other (please specify):,NaN,NaN,More than 50 years,More than 50 years,Blockchain,"10,000 or more employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Bahamas,AED United Arab Emirates dirham,5.000000e+46,Ada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,Not sure/can't remember,NaN,"No, not at all",SEX,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
18463,18464,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,NaN,NaN,11,8,"Developer, back-end",20 to 99 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,"Iran, Islamic Republic of...",IRR\tIranian rial,1.000000e+21,Bash/Shell (all shells);Python,Bash/Shell (all shells);Go;JavaScript;Python,PostgreSQL;Redis,Elasticsearch;MongoDB;PostgreSQL;Redis,Amazon Web Services (AWS),Amazon Web Services (AWS);Google Cloud,FastAPI,FastAPI,NaN,NaN,Composer;Docker,Composer;Docker,IPython;PyCharm;Vim,IPython;PyCharm;Vim,Ubuntu,Ubuntu,Jira;Trello,Jira;Trello,Discord;Google Meet;Jitsi;Skype;Slack;Telegram...,Discord;Google Meet;Skype;Telegram;Whatsapp,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, somewhat",NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,11.0,Strongly agree,Neither agree nor disagree,Agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Strongly agree,Never,6-10 times a week,NaN,30-60 minutes a day,30-60 minutes a day,Microservices;Continuous integration (CI) and ...,NaN,Appropriate in length,Easy,NaN
43556,43557,I agree,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Pluralsight,8,4,"Developer, desktop or enterprise applications",500 to 999 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,Romania,RON\tRomanian leu,1.000000e+16,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,BigQuery;Cosmos DB;Elasticsearch;MariaDB;Micro...,NaN,Amazon Web Services (AWS);Microsoft Azure;VMware,Microsoft Azure;VMware,ASP.NET;ASP.NET CORE,NaN,.NET (5+) ;GTK;MFC;Opencv;OpenGL;Qt,GTK;MFC;Opencv;OpenGL;Qt,Ant;APT;Boost.Test;CMake;cppunit;Dagger;Docker...,Boost.Test;CMake;cppunit;GNU GCC;LLVM's Clang;...,Atom;Code::Blocks;Kate;Nano;Notepad++;Qt Creat...,Kate;Qt Creator;Visual Studio,Cygwin;Ubuntu;Windows,Ubuntu,GitHub Discussions;Markdown File,GitHub Discussions,IRC;Microsoft Teams;Skype,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,Less than once per month or monthly,Yes,Less than once per month or monthly,Neutral,don't,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
49553,49554,I agree,"I am not primarily a developer, but I write co...",25-34 years old,"Employed, full-time",In-person,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,22,5,Research & Development role,"1,000 to 4,999 employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,1.000000e+16,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,NaN,NaN,NaN,NaN,NaN,NaN,NumPy;Pandas,CUDA;GTK;NumPy;Pandas;Qt;Scikit-Learn;TensorFl...,CMake;Docker;Make;MSVC;Ninja;Pip,CMake;LLVM's Clang;Make;Pip,Notepad++;Spyder;Vim;Visual Studio Code,Notepad++;Spyder;Vim;Visual Studio Code,Debian;Windows,Red Hat;Windows,Markdown File;Redmine,Markdown File;Redmine,Microsoft Teams,Microsoft Teams,WolframAlpha,ChatGPT;Google Bard AI;WolframAlpha,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"No, not really",It would be most helpful if the AI could delet...,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,11.0,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,Agree,1-2 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Automated testing;Continuous i...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN
35779,35780,I agree,I am a developer by profession,25-34 years old,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Codecademy;Udemy;Pluralsight;Coursera;Udacity,10,7,NaN,20 to 99 employees,I have a great deal of influence,Investigate,Ask developers I know/work with;Visit develope...,Canada,CAD\tCanadian dollar,1.000000e+15,Assembly;Bash/Shell (all shells);C#;C++;Cobol;...,HTML/CSS;SQL;TypeScript,Cloud Firestore;Elasticsearch;MariaDB;Microsof...,MariaDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,Angular;AngularJS;ASP.NET;ASP.NET CORE;Deno;Ex...,Angular;NestJS,Electron,NaN,Chocolatey;CMake;Composer;Docker;Gradle;npm;We...,Docker;npm,Android Studio;Atom;Eclipse;Goland;IntelliJ ID...,Visual Studio Code,Android;Ubuntu;Windows;Windows Subsystem for L...,Android;Red Hat;Ubuntu;Windows;Windows Subsyst...,Azure Devops;Confluence;Jira;Markdown File;Trello,NaN,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord,ChatGPT,NaN,GitHub Copilot,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,none,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
15439,15440,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,School or academic work,"Associate degree (A.A., A.S., etc.)",Friend or family member,NaN,NaN,4,2,Data or business analyst,20 to 99 employees,I have a great deal of influence,Other,Read ratings or reviews on third party sites l...,Pakistan,KES\tKenyan shilling,4.567887e+12,Apex,Ada,BigQuery,NaN,Amazon Web Services (AWS);Cloudflare;Colocatio...,Managed Hosting;Oracle Cloud Infrastructure (OCI),Angular;AngularJS;ASP.NET;ASP.NET CORE;Blazor;...,NaN,NaN,NaN,Dagger,Dagger,Android Studio,NaN,AIX,NaN,Adobe Workfront,NaN,Cisco Webex Teams,NaN,Andi,NaN,NaN,NaN,Collectives on Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,Gvmhmko,"No, but I plan to soon",Indifferent,NaN,Neither trust nor distrust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,16.0,Neither agree nor disagree,Strongly disagree,Neither agree nor disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6-10 times a week,30-60 minutes a day,Over 120 minutes a day,Continuous integration (CI) and (more often) c...,NaN,Appropriate in length,NaN,NaN
33078,33079,I agree,I am a developer by profession,25-34 years old,"Independent contractor, freelancer, or self-em...",Remote,Freelance/contract work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Formal documentation provided by the owner of ...,NaN,11,8,"Developer, full-stack",2 to 9 employees,I have a great deal of influence,Given a list,Start a free trial;Ask developers I know/work ...,"Iran, Islamic Republic of...",IRR\tIranian rial,1.000000e+11,HTML/CSS;JavaScript;Kotlin;PHP;Python,Dart;HTML/CSS;JavaScript;Kotlin;PHP;Python,MySQL;SQLite,MySQL;SQLite,NaN,NaN,Express;jQuery;Laravel;Next.js;Node.js;React,Express;jQuery;Laravel;Next.js;Node.js;React,Qt,Qt,NaN,NaN,Android Studio;Atom;Notepad++;PhpStorm;Qt Crea...,Android Studio;Atom;Notepad++;PhpStorm;Qt Crea...,Windows,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",NaN,Yes,Very favorable,Increase productivity;Speed up learning,Somewhat trust,Learning about a codebase;Project planning;Wri...,Learning about a codebase;Project planning;Wri...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,2362249.0
19679,19680,I agree,I am a developer by profession,25-34 years old,"Employed, part-time",Remote,Professional development or self-paced learnin...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Other (please specify):,NaN,NaN,9,3,Developer Experience,"Just me - I am a freelancer, sole proprietor, ...",I have little or no influence,NaN,Other (please specify):,Mali,XOF\tWest African CFA franc,2.239672e+10,Ada,Ada,BigQuery,BigQuery,Amazon Web Services (AWS),Amazon Web Services (AWS),Angular,Angular,.NET (5+),.NET (5+),Ansible,Ansible,Android Studio,Android Studio,AIX,AIX,Adobe Workfront,Adobe Workfront,Cisco Webex Teams,Cisco Webex Teams,Andi,Andi,Adrenaline,Adrenaline,Collectives on Stack Overflow,Less than once per month or monthly,Yes,I have never participated in Q&A on Stack Over...,Neutral,Profossionnal,Yes,Very favorable,Other (please explain),Highly trust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,36573181.0
56853,56854,I agree,"I am not primarily a developer, but I write co...",18-24 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Boots...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;edX;Pluralsight;Coursera,12,7,"Developer, QA or test","Just me - I am a freelancer, sole proprietor, ...",I have some influence,Investigate,Ask developers I know/work with;Visit develope...,"Iran, Islamic Republic of...",IRR\tIranian rial,1.980000e+10,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;HTML/CSS;Python;Rus...,MariaDB;MySQL;PostgreSQL;Redis;SQLite,Clickhouse;MariaDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Cloudflare;Digital O...,Cloudflare;Hetzner;Microsoft Azure;Scaleway,Express;Flask;Next.js;Node.js;React;Vue.js,FastAPI;Flask;Next.js;React;Svelte,NaN,NaN,Ansible;APT;Docker;npm;Pip;Webpack;Yarn,Ansible;APT;Docker;Make;Nix;Pip;Yarn,Vim;Visual Studio Code;VSCodium;WebStorm,Vim;Visual Studio Code;VSCodium,Android;Arch;Debian;MacOS;Other Linux-based,Debian;iOS;MacOS;Other Linux-based,Clickup;Confluence;Jira;Markdown File;Miro;Mon...,Markdown File;Miro;Notion;Wikis,Discord;Google Meet;Telegram,Google Meet;Telegram,ChatGPT;You.com,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Collectives on S...,Daily or almost daily,Yes,Daily or almost daily,"Yes, somewhat","It's not mature enough yet, Maybe it can be us...","No, but I plan to soon",Indifferent,NaN,Highly distrust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,7.0,Disagree,Disagree,Disagree,Neither agree nor disagree,Agree,Disagree,Agree,Agree,1-2 times a week,1-2 times a week,Never,60-120 minutes a day,15-30 minutes a day,Automated testing;Continuous integration (CI) ...,"Information Services, IT, Software Development...",Appropriate in length,Neither easy nor difficult,467725.0
9175,9176,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,Primary/elementary school,Colleague,NaN,NaN,NaN,NaN,Academic researcher,"Just me - I am a freelancer, sole proprietor, ...",I have little or no influence,NaN,Start a free trial,Bangladesh,BDT\tBangladeshi taka,1.840199e+10,Ada,NaN,BigQuery,NaN,Amazon Web Services (AWS),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android Studio,Android Studio,Other (Please Specify):,Other (Please Specify):,NaN,NaN,Coolfire Core;Discord;Google Chat;Google Meet;...,Coolfire Core;Discord;Google Chat;Google Meet;...,NaN,NaN,NaN,NaN,Collectives on Stack Overflow,Less than once per month or monthly,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",NaN,Yes,Very favorable,Increase productivity,Highly trust,NaN,Learning about a codebase,NaN,Learning about a codebase,NaN,NaN,NaN,NaN,Yes,People manager,20.0,Strongly disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Never,Never,NaN,Less than 15 minutes a day,Less than 15 minutes a day,Innersource initiative,NaN,Too short,NaN,NaN

In [ ]:
df.nsmallest(10,'Compt)