In [6]:
import pandas as pd
import numpy as np

In [7]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'], 
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'], 
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [8]:
df = pd.DataFrame(people)
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@email.com      NaN
6     NA  Missing                       NA  Missing

In [9]:
# for removing the missing values from the dataframe we have - 'Nan' , 'Missing' 
df.replace('NA',np.nan,inplace=True)
df.replace('Missing',np.nan,inplace=True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [10]:
# df.dropna(axis='index',how='any',subset=['last','email'])
# df.dropna(axis='columns',how='any',subset=['last','email']) # axis = index will work on rows, columns - will work on columns

df.dropna(axis='index',how='all',subset=['last','email'])

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
5    NaN      NaN      Anonymous@email.com  NaN

In [12]:
df.isna()
# it will provide the mask wheather the value is na or not - give true or false based on condition

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [18]:
df.fillna('0',inplace=True)

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@email.com   0
6      0        0                        0   0

In [19]:
df

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@email.com   0
6      0        0                        0   0

In [20]:
df.dtypes

first    str
last     str
email    str
age      str
dtype: object

In [21]:
type(np.nan)

float

In [24]:
df['age'] = df['age'].astype(float) # type cast the value

In [25]:
df.dtypes

first        str
last         str
email        str
age      float64
dtype: object

In [26]:
df['age'].mean()

np.float64(26.714285714285715)

In [27]:
# df.astype() - to convert the Whole dataframe into one datatype as required